# Generated by Django 5.1.2 on 2024-11-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=50)),
                ('setor', models.CharField(max_length=50)),
                ('data_de_admissao', models.DateField()),
                ('salario', models.FloatField()),
            ],
        ),
    ]
