# Generated by Django 5.1.2 on 2024-11-10 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadfun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id_falta', models.AutoField(primary_key=True, serialize=False)),
                ('data_falta', models.DateField()),
                ('motivo', models.CharField(max_length=255)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='cadfun.funcionario')),
                ('id_lancador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faltas_lancadas', to='cadfun.funcionario')),
            ],
        ),
    ]
