# Generated by Django 5.1.2 on 2024-11-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadfun', '0002_falta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falta',
            name='id_lancador',
        ),
    ]
